import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto"
});

export const metadata: Metadata = {
  title: "Service de commande en restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`flex flex-col justify-center items-center max-w-7xl min-h-dvh m-auto border ${roboto.className} bg-fond`}>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
