import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service de commande en restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <QueryProvider>
        <body className="flex flex-col justify-center items-center max-w-7xl min-h-dvh m-auto border">
          {children}
          <Footer/>
        </body>
      </QueryProvider>
    </html>
  );
}
